version: '3'

services:
  gobarber:
    container_name: gobarber
    build: .
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '${APP_PORT}:3333'

networks:
  default:
    external:
      name: devops_backend


volumes:
  gobarber:
