version: '3'

services:
  gobarber:
    build: .
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:home/node/api
      - /home/node/api/node_modules
    ports:
      - '${APP_PORT}:3333'

volumes:
  gobarber:

networks:
  backend:
    driver: bridge
